name: firebase_auth_example
description: A new Flutter project..
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: '>=3.1.2 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

  iproov_firebase:
    path: ../
  firebase_auth: ^4.16.0
  firebase_core: ^2.24.2
  uuid:

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true